/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_script_block_token1 = 1,
  aux_sym_script_block_token2 = 2,
  aux_sym_script_block_token3 = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_AT = 6,
  aux_sym_tag_name_token1 = 7,
  anon_sym_EQ = 8,
  anon_sym_DQUOTE = 9,
  sym_string_content = 10,
  sym_unquoted_value = 11,
  sym_at_unquoted_value = 12,
  anon_sym_SEMI = 13,
  aux_sym_comment_token1 = 14,
  anon_sym_STAR = 15,
  sym_label_name = 16,
  anon_sym_POUND = 17,
  sym_speaker_name = 18,
  sym_text_line = 19,
  sym_inline_text = 20,
  sym_blank_line = 21,
  sym_script_content = 22,
  sym__error_sentinel = 23,
  sym_source_file = 24,
  sym_script_block = 25,
  sym__line = 26,
  sym__statement = 27,
  sym_tag_line = 28,
  sym_tag = 29,
  sym_at_tag = 30,
  sym_tag_name = 31,
  sym_attribute = 32,
  sym_attribute_name = 33,
  sym_attribute_value = 34,
  sym_at_attribute = 35,
  sym_at_attribute_value = 36,
  sym_quoted_string = 37,
  sym_comment = 38,
  sym_label = 39,
  sym_speaker = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_tag_line_repeat1 = 42,
  aux_sym_tag_repeat1 = 43,
  aux_sym_at_tag_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_script_block_token1] = "[iscript]",
  [aux_sym_script_block_token2] = "script_block_token2",
  [aux_sym_script_block_token3] = "[endscript]",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_AT] = "@",
  [aux_sym_tag_name_token1] = "tag_name_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_unquoted_value] = "unquoted_value",
  [sym_at_unquoted_value] = "at_unquoted_value",
  [anon_sym_SEMI] = ";",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_STAR] = "*",
  [sym_label_name] = "label_name",
  [anon_sym_POUND] = "#",
  [sym_speaker_name] = "speaker_name",
  [sym_text_line] = "text_line",
  [sym_inline_text] = "inline_text",
  [sym_blank_line] = "blank_line",
  [sym_script_content] = "script_content",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_source_file] = "source_file",
  [sym_script_block] = "script_block",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_tag_line] = "tag_line",
  [sym_tag] = "tag",
  [sym_at_tag] = "at_tag",
  [sym_tag_name] = "tag_name",
  [sym_attribute] = "attribute",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_at_attribute] = "at_attribute",
  [sym_at_attribute_value] = "at_attribute_value",
  [sym_quoted_string] = "quoted_string",
  [sym_comment] = "comment",
  [sym_label] = "label",
  [sym_speaker] = "speaker",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tag_line_repeat1] = "tag_line_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_at_tag_repeat1] = "at_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_script_block_token1] = aux_sym_script_block_token1,
  [aux_sym_script_block_token2] = aux_sym_script_block_token2,
  [aux_sym_script_block_token3] = aux_sym_script_block_token3,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_tag_name_token1] = aux_sym_tag_name_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_unquoted_value] = sym_unquoted_value,
  [sym_at_unquoted_value] = sym_at_unquoted_value,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_label_name] = sym_label_name,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_speaker_name] = sym_speaker_name,
  [sym_text_line] = sym_text_line,
  [sym_inline_text] = sym_inline_text,
  [sym_blank_line] = sym_blank_line,
  [sym_script_content] = sym_script_content,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym_script_block] = sym_script_block,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_tag_line] = sym_tag_line,
  [sym_tag] = sym_tag,
  [sym_at_tag] = sym_at_tag,
  [sym_tag_name] = sym_tag_name,
  [sym_attribute] = sym_attribute,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_at_attribute] = sym_at_attribute,
  [sym_at_attribute_value] = sym_at_attribute_value,
  [sym_quoted_string] = sym_quoted_string,
  [sym_comment] = sym_comment,
  [sym_label] = sym_label,
  [sym_speaker] = sym_speaker,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tag_line_repeat1] = aux_sym_tag_line_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_at_tag_repeat1] = aux_sym_at_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_script_block_token1] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_script_block_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_script_block_token3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym_at_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_label_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_speaker_name] = {
    .visible = true,
    .named = true,
  },
  [sym_text_line] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_text] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_script_content] = {
    .visible = true,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_script_block] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_tag_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_at_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_at_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_at_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_speaker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_at_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 9,
  [21] = 13,
  [22] = 11,
  [23] = 19,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 25,
  [37] = 24,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 35,
  [48] = 48,
  [49] = 49,
  [50] = 49,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '"', 41,
        '#', 51,
        '*', 49,
        ';', 46,
        '=', 40,
        '@', 38,
        '[', 36,
        ']', 37,
        '\t', 2,
        ' ', 2,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(33);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '"', 41,
        '#', 51,
        '*', 49,
        ';', 46,
        '=', 40,
        '@', 38,
        '[', 36,
        ']', 37,
        '\t', 2,
        ' ', 2,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '#', 51,
        '*', 49,
        ';', 46,
        '@', 38,
        '[', 36,
        '\t', 3,
        ' ', 3,
      );
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(57);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 57,
        '\r', 4,
        '#', 51,
        '*', 49,
        ';', 46,
        '@', 38,
        '[', 36,
        '\t', 5,
        ' ', 5,
      );
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ']') ADVANCE(44);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(45);
      END_STATE();
    case 8:
      if (lookahead == '[') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == ']') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == ']') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(50);
      END_STATE();
    case 27:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '#', 51,
        '*', 49,
        ';', 46,
        '@', 38,
        '[', 36,
        '\t', 3,
        ' ', 3,
      );
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 28:
      if (eof) ADVANCE(31);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 29:
      if (eof) ADVANCE(31);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '\n', 57,
        '\r', 4,
        '#', 51,
        '*', 49,
        ';', 46,
        '@', 38,
        '[', 36,
        '\t', 5,
        ' ', 5,
      );
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_script_block_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_script_block_token2);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_script_block_token3);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ']') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_at_unquoted_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_label_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_speaker_name);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_speaker_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_text_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_inline_text);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[') ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_inline_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '[') ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_blank_line);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 27},
  [5] = {.lex_state = 27},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 30},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 28},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 28},
  [25] = {.lex_state = 28},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 29},
  [36] = {.lex_state = 28},
  [37] = {.lex_state = 28},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 42},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 8, .external_lex_state = 2},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 29},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 47},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 26},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_script_block_token1] = ACTIONS(1),
    [aux_sym_script_block_token2] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_tag_name_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_blank_line] = ACTIONS(1),
    [sym_script_content] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym_script_block] = STATE(2),
    [sym__line] = STATE(2),
    [sym__statement] = STATE(45),
    [sym_tag_line] = STATE(45),
    [sym_tag] = STATE(9),
    [sym_at_tag] = STATE(45),
    [sym_comment] = STATE(45),
    [sym_label] = STATE(45),
    [sym_speaker] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_script_block_token1] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_text_line] = ACTIONS(17),
    [sym_blank_line] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      aux_sym_script_block_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(9), 1,
      anon_sym_AT,
    ACTIONS(11), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      anon_sym_STAR,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_text_line,
    ACTIONS(25), 1,
      sym_blank_line,
    STATE(9), 1,
      sym_tag,
    STATE(3), 3,
      sym_script_block,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(48), 6,
      sym__statement,
      sym_tag_line,
      sym_at_tag,
      sym_comment,
      sym_label,
      sym_speaker,
  [44] = 12,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      aux_sym_script_block_token1,
    ACTIONS(32), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_AT,
    ACTIONS(38), 1,
      anon_sym_SEMI,
    ACTIONS(41), 1,
      anon_sym_STAR,
    ACTIONS(44), 1,
      anon_sym_POUND,
    ACTIONS(47), 1,
      sym_text_line,
    ACTIONS(50), 1,
      sym_blank_line,
    STATE(20), 1,
      sym_tag,
    STATE(3), 3,
      sym_script_block,
      sym__line,
      aux_sym_source_file_repeat1,
    STATE(51), 6,
      sym__statement,
      sym_tag_line,
      sym_at_tag,
      sym_comment,
      sym_label,
      sym_speaker,
  [88] = 3,
    ACTIONS(55), 1,
      aux_sym_script_block_token2,
    ACTIONS(57), 2,
      anon_sym_LBRACK,
      sym_blank_line,
    ACTIONS(53), 7,
      ts_builtin_sym_end,
      aux_sym_script_block_token1,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_POUND,
      sym_text_line,
  [105] = 3,
    ACTIONS(61), 1,
      aux_sym_script_block_token2,
    ACTIONS(63), 2,
      anon_sym_LBRACK,
      sym_blank_line,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      aux_sym_script_block_token1,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_POUND,
      sym_text_line,
  [122] = 2,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 8,
      ts_builtin_sym_end,
      aux_sym_script_block_token1,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_POUND,
      sym_text_line,
      sym_blank_line,
  [136] = 2,
    ACTIONS(67), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 8,
      ts_builtin_sym_end,
      aux_sym_script_block_token1,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_POUND,
      sym_text_line,
      sym_blank_line,
  [150] = 2,
    ACTIONS(71), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 8,
      ts_builtin_sym_end,
      aux_sym_script_block_token1,
      anon_sym_AT,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_POUND,
      sym_text_line,
      sym_blank_line,
  [164] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      aux_sym_script_block_token2,
    ACTIONS(77), 1,
      sym_inline_text,
    STATE(13), 2,
      sym_tag,
      aux_sym_tag_line_repeat1,
  [181] = 4,
    ACTIONS(81), 1,
      aux_sym_tag_name_token1,
    STATE(27), 1,
      sym_attribute_name,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
    STATE(14), 2,
      sym_at_attribute,
      aux_sym_at_tag_repeat1,
  [196] = 5,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      aux_sym_script_block_token2,
    ACTIONS(87), 1,
      anon_sym_LBRACK,
    ACTIONS(90), 1,
      sym_inline_text,
    STATE(11), 2,
      sym_tag,
      aux_sym_tag_line_repeat1,
  [213] = 4,
    ACTIONS(81), 1,
      aux_sym_tag_name_token1,
    STATE(27), 1,
      sym_attribute_name,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
    STATE(10), 2,
      sym_at_attribute,
      aux_sym_at_tag_repeat1,
  [228] = 5,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      aux_sym_script_block_token2,
    ACTIONS(99), 1,
      sym_inline_text,
    STATE(11), 2,
      sym_tag,
      aux_sym_tag_line_repeat1,
  [245] = 4,
    ACTIONS(103), 1,
      aux_sym_tag_name_token1,
    STATE(27), 1,
      sym_attribute_name,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
    STATE(14), 2,
      sym_at_attribute,
      aux_sym_at_tag_repeat1,
  [260] = 4,
    ACTIONS(81), 1,
      aux_sym_tag_name_token1,
    ACTIONS(106), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      sym_attribute_name,
    STATE(18), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [274] = 4,
    ACTIONS(81), 1,
      aux_sym_tag_name_token1,
    ACTIONS(108), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      sym_attribute_name,
    STATE(18), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [288] = 1,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
      anon_sym_RBRACK,
      aux_sym_tag_name_token1,
      anon_sym_EQ,
  [296] = 4,
    ACTIONS(112), 1,
      anon_sym_RBRACK,
    ACTIONS(114), 1,
      aux_sym_tag_name_token1,
    STATE(32), 1,
      sym_attribute_name,
    STATE(18), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [310] = 4,
    ACTIONS(81), 1,
      aux_sym_tag_name_token1,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      sym_attribute_name,
    STATE(15), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [324] = 4,
    ACTIONS(75), 1,
      aux_sym_script_block_token2,
    ACTIONS(119), 1,
      anon_sym_LBRACK,
    ACTIONS(121), 1,
      sym_inline_text,
    STATE(21), 2,
      sym_tag,
      aux_sym_tag_line_repeat1,
  [338] = 4,
    ACTIONS(97), 1,
      aux_sym_script_block_token2,
    ACTIONS(119), 1,
      anon_sym_LBRACK,
    ACTIONS(123), 1,
      sym_inline_text,
    STATE(22), 2,
      sym_tag,
      aux_sym_tag_line_repeat1,
  [352] = 4,
    ACTIONS(85), 1,
      aux_sym_script_block_token2,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(128), 1,
      sym_inline_text,
    STATE(22), 2,
      sym_tag,
      aux_sym_tag_line_repeat1,
  [366] = 4,
    ACTIONS(81), 1,
      aux_sym_tag_name_token1,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      sym_attribute_name,
    STATE(16), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
  [380] = 2,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      sym_inline_text,
    ACTIONS(135), 2,
      aux_sym_script_block_token2,
      anon_sym_LBRACK,
  [389] = 2,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      sym_inline_text,
    ACTIONS(139), 2,
      aux_sym_script_block_token2,
      anon_sym_LBRACK,
  [398] = 1,
    ACTIONS(141), 4,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
      anon_sym_RBRACK,
      aux_sym_tag_name_token1,
  [405] = 2,
    ACTIONS(145), 1,
      anon_sym_EQ,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
      aux_sym_tag_name_token1,
  [414] = 1,
    ACTIONS(147), 4,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
      anon_sym_RBRACK,
      aux_sym_tag_name_token1,
  [421] = 4,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    ACTIONS(151), 1,
      sym_unquoted_value,
    STATE(42), 1,
      sym_quoted_string,
    STATE(43), 1,
      sym_attribute_value,
  [434] = 4,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    ACTIONS(153), 1,
      sym_at_unquoted_value,
    STATE(33), 1,
      sym_quoted_string,
    STATE(34), 1,
      sym_at_attribute_value,
  [447] = 1,
    ACTIONS(155), 4,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
      anon_sym_RBRACK,
      aux_sym_tag_name_token1,
  [454] = 2,
    ACTIONS(159), 1,
      anon_sym_EQ,
    ACTIONS(157), 2,
      anon_sym_RBRACK,
      aux_sym_tag_name_token1,
  [462] = 1,
    ACTIONS(161), 3,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
      aux_sym_tag_name_token1,
  [468] = 1,
    ACTIONS(163), 3,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
      aux_sym_tag_name_token1,
  [474] = 3,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(167), 1,
      aux_sym_script_block_token2,
    ACTIONS(169), 1,
      sym_speaker_name,
  [484] = 2,
    ACTIONS(137), 1,
      sym_inline_text,
    ACTIONS(139), 2,
      aux_sym_script_block_token2,
      anon_sym_LBRACK,
  [492] = 2,
    ACTIONS(133), 1,
      sym_inline_text,
    ACTIONS(135), 2,
      aux_sym_script_block_token2,
      anon_sym_LBRACK,
  [500] = 1,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
  [505] = 1,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
  [510] = 2,
    ACTIONS(175), 1,
      aux_sym_tag_name_token1,
    STATE(12), 1,
      sym_tag_name,
  [517] = 2,
    ACTIONS(177), 1,
      anon_sym_DQUOTE,
    ACTIONS(179), 1,
      sym_string_content,
  [524] = 1,
    ACTIONS(181), 2,
      anon_sym_RBRACK,
      aux_sym_tag_name_token1,
  [529] = 1,
    ACTIONS(183), 2,
      anon_sym_RBRACK,
      aux_sym_tag_name_token1,
  [534] = 2,
    ACTIONS(185), 1,
      aux_sym_script_block_token3,
    ACTIONS(187), 1,
      sym_script_content,
  [541] = 2,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(189), 1,
      aux_sym_script_block_token2,
  [548] = 1,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      aux_sym_script_block_token2,
  [553] = 2,
    ACTIONS(167), 1,
      aux_sym_script_block_token2,
    ACTIONS(169), 1,
      sym_speaker_name,
  [560] = 2,
    ACTIONS(189), 1,
      aux_sym_script_block_token2,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [567] = 2,
    ACTIONS(175), 1,
      aux_sym_tag_name_token1,
    STATE(19), 1,
      sym_tag_name,
  [574] = 2,
    ACTIONS(175), 1,
      aux_sym_tag_name_token1,
    STATE(23), 1,
      sym_tag_name,
  [581] = 1,
    ACTIONS(189), 1,
      aux_sym_script_block_token2,
  [585] = 1,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
  [589] = 1,
    ACTIONS(197), 1,
      aux_sym_script_block_token2,
  [593] = 1,
    ACTIONS(199), 1,
      aux_sym_comment_token1,
  [597] = 1,
    ACTIONS(201), 1,
      aux_sym_script_block_token3,
  [601] = 1,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
  [605] = 1,
    ACTIONS(205), 1,
      sym_label_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 88,
  [SMALL_STATE(5)] = 105,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 136,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 164,
  [SMALL_STATE(10)] = 181,
  [SMALL_STATE(11)] = 196,
  [SMALL_STATE(12)] = 213,
  [SMALL_STATE(13)] = 228,
  [SMALL_STATE(14)] = 245,
  [SMALL_STATE(15)] = 260,
  [SMALL_STATE(16)] = 274,
  [SMALL_STATE(17)] = 288,
  [SMALL_STATE(18)] = 296,
  [SMALL_STATE(19)] = 310,
  [SMALL_STATE(20)] = 324,
  [SMALL_STATE(21)] = 338,
  [SMALL_STATE(22)] = 352,
  [SMALL_STATE(23)] = 366,
  [SMALL_STATE(24)] = 380,
  [SMALL_STATE(25)] = 389,
  [SMALL_STATE(26)] = 398,
  [SMALL_STATE(27)] = 405,
  [SMALL_STATE(28)] = 414,
  [SMALL_STATE(29)] = 421,
  [SMALL_STATE(30)] = 434,
  [SMALL_STATE(31)] = 447,
  [SMALL_STATE(32)] = 454,
  [SMALL_STATE(33)] = 462,
  [SMALL_STATE(34)] = 468,
  [SMALL_STATE(35)] = 474,
  [SMALL_STATE(36)] = 484,
  [SMALL_STATE(37)] = 492,
  [SMALL_STATE(38)] = 500,
  [SMALL_STATE(39)] = 505,
  [SMALL_STATE(40)] = 510,
  [SMALL_STATE(41)] = 517,
  [SMALL_STATE(42)] = 524,
  [SMALL_STATE(43)] = 529,
  [SMALL_STATE(44)] = 534,
  [SMALL_STATE(45)] = 541,
  [SMALL_STATE(46)] = 548,
  [SMALL_STATE(47)] = 553,
  [SMALL_STATE(48)] = 560,
  [SMALL_STATE(49)] = 567,
  [SMALL_STATE(50)] = 574,
  [SMALL_STATE(51)] = 581,
  [SMALL_STATE(52)] = 585,
  [SMALL_STATE(53)] = 589,
  [SMALL_STATE(54)] = 593,
  [SMALL_STATE(55)] = 597,
  [SMALL_STATE(56)] = 601,
  [SMALL_STATE(57)] = 605,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_block, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_block, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_block, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_block, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_block, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_block, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_line, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_line, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_at_tag, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_at_tag, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_line, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_line, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_at_tag_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_at_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_line_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_at_attribute, 1, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_at_attribute_value, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_at_attribute, 3, 0, 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_speaker, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_speaker, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_speaker, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [203] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_script_content = 0,
  ts_external_token__error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_script_content] = sym_script_content,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_script_content] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_script_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_tyranoscript_external_scanner_create(void);
void tree_sitter_tyranoscript_external_scanner_destroy(void *);
bool tree_sitter_tyranoscript_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_tyranoscript_external_scanner_serialize(void *, char *);
void tree_sitter_tyranoscript_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tyranoscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_tyranoscript_external_scanner_create,
      tree_sitter_tyranoscript_external_scanner_destroy,
      tree_sitter_tyranoscript_external_scanner_scan,
      tree_sitter_tyranoscript_external_scanner_serialize,
      tree_sitter_tyranoscript_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "tyranoscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
